version: '3.8'
services:
  app:
    user: 1000:1000
    build:
      context: .
      args:
          UID: 1000
          GID: 1000
          USERNAME: "node"
    volumes:
      - "$SSH_AUTH_SOCK:/tmp/ssh-agent.sock"
    environment:
      SSH_AUTH_SOCK: "/tmp/ssh-agent.sock"